- name: Create Jenkins Jobs 
  hosts: localhost
  connection: local
  vars:
    sjobs: 
     - { git_repo_url: https://github.com/arrvinddev/roboshop-terraform.git, job_name: roboshop-terraform  }
     - { git_repo_url: https://github.com/arrvinddev/roboshop-ansible.git, job_name: roboshop-ansible  }

  tasks: 
  - name: Create Job Block
    loop: "{{sjobs}}"
    block: 
      - name: Copy Xml File
        ansible.builtin.template:
          src: test.xml 
          dest: /tmp/test.xml

      - name: Create Jenkins Jobs
        community.general.jenkins_job:
          config: "{{ lookup ('file', 'test.xml' )}}"
          name: "{{item.job_name}}"
          password: admin123 
          url: http://172.31.86.68:8080
          user: admin
