sjobs: 
  - { git_repo_url: https://github.com/arrvinddev/roboshop-terraform.git, job_name: roboshop-terraform, file_name: Jenkinsfile  }
  - { git_repo_url: https://github.com/arrvinddev/roboshop-ansible.git, job_name: roboshop-ansible, file_name: Jenkinsfile  }
  - { git_repo_url: https://github.com/arrvinddev/aws-ssm-parameter-store.git, job_name: aws-ssm-parameter-store, file_name: Jenkinsfile  }
  - { git_repo_url: https://github.com/arrvinddev/aws-ssm-parameter-store.git, job_name: aws-ssm-parameter-store-ps-docker, file_name: Jenkinsfile-ps  }
  - { git_repo_url: https://github.com/arrvinddev/roboshop-helm.git, job_name: roboshop-helm, file_name: Jenkinsfile  }
  - { git_repo_url: https://github.com/arrvinddev/schema-loader.git, job_name: schema-loader, file_name: Jenkinsfile  }


mjobs: 
  - { git_repo_url: https://github.com/arrvinddev/cart.git, job_name: cart  }
  - { git_repo_url: https://github.com/arrvinddev/catalogue.git, job_name: catalogue  }
  - { git_repo_url: https://github.com/arrvinddev/user.git, job_name: user  }
  - { git_repo_url: https://github.com/arrvinddev/shipping.git, job_name: shipping  }
  - { git_repo_url: https://github.com/arrvinddev/payment.git, job_name: payment  }
  - { git_repo_url: https://github.com/arrvinddev/dispatch.git, job_name: dispatch  }
  - { git_repo_url: https://github.com/arrvinddev/frontend.git, job_name: frontend  }
 